## Deliverable 2. Create a Customer Travel Destinations Map.

In [6]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [9]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("Weather_Database/WeatherPy_Database.csv")
city_data_df.head()

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Weather Description
0,0,Vaini,-21.2000,-175.2000,82.56,83,20,5.75,few clouds
1,1,Bumba,2.1833,22.4667,70.25,94,97,2.86,light rain
2,2,Punta Arenas,-53.1500,-70.9167,39.31,81,0,27.63,light rain
3,3,Atuona,-9.8000,-139.0333,77.11,78,31,11.12,scattered clouds
4,4,Grindavik,63.8424,-22.4338,55.56,100,90,21.85,overcast clouds

In [10]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

In [11]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Weather Description
0,0,Vaini,-21.2000,-175.2000,82.56,83,20,5.75,few clouds
3,3,Atuona,-9.8000,-139.0333,77.11,78,31,11.12,scattered clouds
5,5,Westport,41.1415,-73.3579,75.97,74,58,3.00,broken clouds
8,8,Sibolga,1.7427,98.7792,82.63,67,87,1.21,overcast clouds
15,15,Hilo,19.7297,-155.0900,87.28,83,90,10.36,light rain
19,19,Campoverde,-8.4753,-74.8058,76.69,69,5,1.23,clear sky
20,20,Kapaa,22.0752,-159.3190,84.18,83,90,4.00,mist
21,21,Oriximina,-1.7656,-55.8661,77.97,68,37,3.91,scattered clouds
26,26,Hithadhoo,-0.6000,73.0833,80.82,74,74,2.01,broken clouds
29,29,San Andres,12.5847,-81.7006,82.42,83,75,11.50,broken clouds

In [12]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

City_ID                255
City                   255
Lat                    255
Lng                    255
Max Temp               255
Humidity               255
Cloudiness             255
Wind Speed             255
Weather Description    255
dtype: int64

In [14]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
preferred_cities_df_clean = preferred_cities_df.dropna()

In [15]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df_clean[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

KeyError: "['Current Description', 'Country'] not in index"

In [8]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.

    # 6c. Get latitude and longitude from DataFrame

    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    

    # 6e. Make request and retrieve the JSON data from the search. 
   
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.

In [9]:
# 7. Drop the rows where there is no Hotel Name.

In [10]:
# 8a. Create the output File (CSV)

# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [11]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """

"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [12]:
# 11a. Add a marker layer for each city to the map. 

# 11b. Display the figure